title: Lucas Boczkowski
logo: /assets/img/Lucas_profile_pic.png
description: >
  Information systems engineer. Product Owner. Data Scientist.

  Contact Information:
  Córdoba - Argentina**
  Phone**: +54 9 351 3543654
  LinkedIn https://www.linkedin.com/in/lucasboczkowski/
  Email**: boczkowskilucas@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
