title: Lucas Boczkowski
logo: /assets/img/Lucas_profile_pic.png
description:
Information systems engineer. Product Owner. Data Scientist.
Contact Indformation:
- **Córdoba - Argentina**
- **Phone**: [(+54) 9 351 3543654](tel:+543513543654)
- **LinkedIn**: [Lucas Boczkowski](https://www.linkedin.com/in/lucasboczkowski/)
- **Email**: [boczkowskilucas@gmail.com](mailto:boczkowskilucas@gmail.com)
show_downloads: true
theme: jekyll-theme-minimal
